name: Hello World
author: Sangkhuu
description: Hello there,

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Sangkhuu

outputs:
  time:
    description: 'The greeting time'

runs:
  using: 'node12'
  main: 'dist/index.js'
  